# Generated by Django 4.2 on 2024-05-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('create_publication', 'изменение публикации'), ('create_title', 'изменение описания'), ('create_category', 'изменение категории')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
