# Generated by Django 5.0.3 on 2024-03-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_contact_name_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=250, verbose_name='Описание продукта'),
        ),
    ]
